import {test, expect} from '@playwright/test';

test('evidence to script workflow blocks synthetic broadcast review', async ({page}) => {
  await page.goto('/');
  await expect(page.getByRole('heading', {name:'Control center'})).toBeVisible();
  await expect(page.getByText('Local service connected')).toBeVisible();
  await page.getByRole('button', {name:'Load training dataset'}).click();
  await expect(page.getByRole('status').filter({hasText:'Synthetic training dataset loaded'})).toBeVisible();
  await page.getByRole('button', {name:/Training Cyclone.*Jan 01, 2024, 18:00/}).click();
  await expect(page.getByRole('heading', {name:'What changed?'})).toBeVisible();
  await expect(page.locator('.changes')).toContainText('85');
  await expect(page.locator('.changes')).toContainText('100');
  await page.getByRole('button', {name:'Create source-linked script'}).click();
  await expect(page.getByRole('heading', {name:'Script Editor', exact:true})).toBeVisible();
  await expect(page.locator('.script-text')).toContainText('synthetic scenario is not a weather observation');
  await expect(page.locator('.script-text')).toContainText('85 to 100 mph');
  await page.getByLabel('REVIEWER NAME').fill('Browser test editor');
  await page.getByRole('button', {name:'Record editorial review'}).click();
  await expect(page.getByRole('alert')).toContainText('remain blocked');
  const download = page.waitForEvent('download');
  await page.getByRole('link', {name:'Export scene plan CSV'}).click();
  expect((await download).suggestedFilename()).toBe('scene-plan.csv');
  await page.reload();
  await page.getByRole('button', {name:'Script Editor', exact:true}).click();
  await expect(page.locator('.script-text')).toContainText('85 to 100 mph');
  await page.screenshot({path:'test-results/newsroom.png', fullPage:true});
});

test('capabilities and planned modules report actual state', async ({page}) => {
  await page.goto('/');
  await page.getByRole('button', {name:'OBS Controller', exact:true}).click();
  await expect(page.getByText('Phase 6 · not connected')).toBeVisible();
  await page.getByRole('button', {name:'Settings', exact:false}).click();
  await expect(page.getByRole('heading', {name:'Runtime capabilities'})).toBeVisible();
  await expect(page.locator('.settings-rows')).toContainText('ffmpeg');
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('heading', {name:'Settings', exact:true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('intelligence filters, verification timeline and paused polling settings work', async ({page, request}) => {
  await page.goto('/');
  await expect(page.getByText('Local service connected')).toBeVisible();
  await page.getByRole('button', {name:'Weather Intelligence', exact:true}).click();
  await expect(page.getByText('NWS active alerts', {exact:true})).toBeVisible();
  await expect(page.getByText('NHC Atlantic advisories', {exact:true})).toBeVisible();
  await page.getByLabel('Evidence provider').selectOption('TRAINING');
  await page.getByLabel('Evidence versions').selectOption('all');
  await expect(page.locator('.archive-panel .event-row')).toHaveCount(2);
  await page.getByLabel('Search weather evidence').fill('no matching place');
  await expect(page.getByRole('heading', {name:'No matching evidence'})).toBeVisible();
  await page.getByLabel('Search weather evidence').clear();
  await page.locator('.archive-panel .event-row').first().click();
  await expect(page.getByRole('heading', {name:'Evidence verification'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Visual evidence timeline'})).toBeVisible();
  await expect(page.locator('.evidence-timeline button')).toHaveCount(2);
  await page.getByLabel('NWS polling interval').selectOption('60');
  await expect(page.getByRole('status').filter({hasText:'NWS automatic collection paused'})).toBeVisible();
  const response = await request.get('/api/intelligence');
  const feed = (await response.json()).feeds.find((value:{id:string}) => value.id === 'nws');
  expect(feed.enabled).toBe(false);
  expect(feed.interval_seconds).toBe(60);
  await page.reload();
  await page.getByRole('button', {name:'Weather Intelligence', exact:true}).click();
  await expect(page.getByLabel('NWS polling interval')).toHaveValue('60');
  await expect(page.getByRole('button', {name:'Start polling NWS'})).toBeVisible();
  await page.screenshot({path:'test-results/weather-intelligence.png',fullPage:true});
});

test('newsroom handoffs, revision history and unsupported edits work in the browser', async ({page, request}) => {
  await request.post('/api/training/load');
  await page.goto('/');
  await expect(page.getByText('Local service connected')).toBeVisible();
  await page.getByRole('button', {name:'AI Newsroom', exact:true}).click();
  const evidence = page.getByLabel('SOURCE EVIDENCE');
  await evidence.selectOption('training:cyclone:2');
  await expect(page.getByLabel('WRITER')).toHaveValue('deterministic');
  await page.getByRole('button', {name:'Run newsroom', exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'Six newsroom roles completed'})).toBeVisible();
  await expect(page.locator('.agent-handoff')).toHaveCount(6);
  await page.locator('.agent-handoff').nth(3).locator('summary').first().click();
  await expect(page.locator('.agent-handoff').nth(3)).toContainText('evidence_manifest');
  await page.getByRole('button', {name:'Open draft', exact:true}).click();
  await expect(page.locator('.script-text')).toContainText('85 to 100 mph');
  await page.getByRole('button', {name:'Edit narration'}).click();
  const narration = page.getByLabel('NARRATION TEXT');
  const original = await narration.inputValue();
  await narration.fill(original + '\n\nUnsupported test claim: landfall tomorrow with 200 mph winds.');
  await page.getByLabel('EDITOR NAME', {exact:true}).fill('Browser revision editor');
  await page.getByLabel('REVISION NOTE').fill('Exercise the unsupported claim gate');
  await page.getByRole('button', {name:'Save new revision'}).click();
  await expect(page.getByRole('status').filter({hasText:'New revision saved'})).toBeVisible();
  await expect(page.locator('.claim-card.unsupported')).toHaveCount(1);
  await expect(page.locator('.editorial-issues')).toContainText('requires a named source attestation');
  await page.getByLabel('REVIEWER NAME').fill('Browser editor');
  await page.getByRole('button', {name:'Record editorial review'}).click();
  await expect(page.getByRole('alert')).toContainText('remain blocked');
  await page.getByLabel('REVISION HISTORY').selectOption('1');
  await expect(page.locator('.script-text')).not.toContainText('Unsupported test claim');
  await expect(page.getByRole('button', {name:'Record editorial review'})).toBeDisabled();
  await page.getByLabel('REVISION HISTORY').selectOption('latest');
  await expect(page.locator('.script-text')).toContainText('Unsupported test claim');
  await page.reload();
  await page.getByRole('button', {name:'Script Editor', exact:true}).click();
  await expect(page.locator('.script-text')).toContainText('Unsupported test claim');
  await expect(page.getByLabel('REVISION HISTORY')).toContainText('Latest · revision 2');
  const scriptId = await page.getByLabel('SELECT DRAFT').inputValue();
  const document = await (await request.get(`/api/scripts/${scriptId}`)).json();
  expect(document.broadcast_eligible).toBe(false);
  expect(document.revision).toBe(2);
  expect(document.editorial.can_review).toBe(false);
  await page.screenshot({path:'test-results/phase-3-editor.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('edited claims retain named source attestations and remain training-only', async ({page, request}) => {
  await request.post('/api/training/load');
  const draft = await (await request.post('/api/scripts', {data:{advisory_id:'training:cyclone:2'}})).json();
  await page.goto('/');
  await expect(page.getByText('Local service connected')).toBeVisible();
  await page.getByRole('button', {name:'Script Editor', exact:true}).click();
  await page.getByLabel('SELECT DRAFT').selectOption(draft.id);
  await page.getByRole('button', {name:'Edit narration'}).click();
  const narration = page.getByLabel('NARRATION TEXT');
  await narration.fill(draft.text + '\n\nIn this training scenario, maximum winds are reported at 100 mph.');
  await page.getByLabel('EDITOR NAME', {exact:true}).fill('Browser claim editor');
  await page.getByLabel('REVISION NOTE').fill('Add supported training measurement');
  await page.getByRole('button', {name:'Save new revision'}).click();
  await expect(page.getByRole('status').filter({hasText:'New revision saved'})).toBeVisible();
  await expect(page.locator('.claim-card.unsupported')).toHaveCount(1);
  await page.getByLabel('REVIEWER NAME').fill('Browser source checker');
  await page.getByRole('button', {name:'Read preserved source'}).click();
  const sourceText = await page.locator('.source-quote-preview').textContent();
  expect(sourceText).toContain('SYNTHETIC TRAINING SCENARIO');
  await page.getByLabel('EXACT SUPPORTING QUOTE').fill(sourceText!);
  await page.getByLabel('WHY THIS QUOTE SUPPORTS THE CLAIM').fill('The synthetic scenario contains the same wind measurement; this is training-only.');
  await page.getByRole('button', {name:'Record source attestation'}).click();
  await expect(page.getByRole('status').filter({hasText:'Source attestation saved'})).toBeVisible();
  await expect(page.locator('.claim-card.unsupported')).toHaveCount(0);
  const doc = await (await request.get(`/api/scripts/${draft.id}`)).json();
  expect(doc.revision).toBe(3);
  expect(doc.claims.at(-1).status).toBe('human_attested');
  expect(doc.claims.at(-1).support.reviewer).toBe('Browser source checker');
  expect(doc.editorial.can_review).toBe(false);
  await page.getByRole('button', {name:'Record editorial review'}).click();
  await expect(page.getByRole('alert')).toContainText('remain blocked');
  await page.reload();
  await page.getByRole('button', {name:'Script Editor', exact:true}).click();
  await page.getByLabel('SELECT DRAFT').selectOption(draft.id);
  const supported = page.locator('.claim-card').filter({hasText:'human attested'});
  await supported.locator('summary').click();
  await expect(supported).toContainText('Verified by Browser source checker');
  await page.screenshot({path:'test-results/phase-3-attestation.png',fullPage:true});
});
